### ISSUE TITLE
output color cannot be turned off

### ISSUE THREAD

**Issue by juniorhero** [ffuf/ffuf#329] opened 2020-10-12 22:02 UTC
-c               Colorize output. (default: false)
this parameter has no effect on the output both on the verbose and non-verbose

I want no colors on the output, so I set it to -c false but still green color on the output did not go

**Comment by bsysop** [comment] 2020-10-13 00:13
Hi @juniorhero 

-c means you will "colorize" the output
By default FFUF don't colorize, if you want colorize you add `-c` at your arguments, otherwise just don't.

Happy hacking!.

**Comment by juniorhero** [comment] 2020-10-13 05:47
Without using the -c by default the colorize is turned on.

I need to disable it.

**Comment by jimen0** [comment] 2020-10-16 14:52
Hi @juniorhero,

Do you know from what commit your ffuf copy was built? I just tested current HEAD (`602c1c79e8399ccae5f6f7d645ab4f8e47e77118`) built using Go 1.15.3 and tip branch and the color flag worked as expected.

With the flag (coloring enabled):
![image](https://user-images.githubusercontent.com/6826244/96273423-a07b1580-0fcf-11eb-918b-8eac714bdf5b.png)


Without the flag (coloring disabled):
![image](https://user-images.githubusercontent.com/6826244/96273474-ad980480-0fcf-11eb-9b37-f15f626e6c7b.png)

Tag `v1.1.0` also seems to be working as expected.

**Comment by joohoi** [comment] 2020-11-16 17:01
I am not able to reproduce the issue either. So for now, I'll close this issue, feel free to comment again if you think this is still valid.

**Closed by joohoi** 2020-11-16 17:01 UTC
