### ISSUE TITLE
Error: go/src/github.com/ffuf/ffuf/pkg/runner/simple.go:36:19: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport

### ISSUE THREAD

**Issue by marataziat** [ffuf/ffuf#29] opened 2019-04-20 13:23 UTC
```
marat@DESKTOP-FU7J5OI:~$ go get github.com/ffuf/ffuf

# github.com/ffuf/ffuf/pkg/runner
go/src/github.com/ffuf/ffuf/pkg/runner/simple.go:36:19: unknown field 'MaxConnsPerHost' in struct literal of type http.Transport
```

**Comment by joohoi** [comment] 2019-04-20 13:25
This is caused by too old version of Go compiler. You are going to need Go >= 1.11 as noted in the readme. I'm closing the issue as resolved, if you have further issues, please comment and I'll reopen if needed.

**Closed by joohoi** 2019-04-20 13:25 UTC
