### ISSUE TITLE
[Feature/Issue/Question] Allow match regex to filter headers and filter/match header sizes.

### ISSUE THREAD

**Issue by Shaddy** [ffuf/ffuf#68] opened 2019-09-21 12:10 UTC
I did not many tests to confirm this but seems that filter regex or match regex only apply to response body/content. 

Is there anything stopping from at least, filtering also header responses?

Also, would be interesting to use headers size, since this is currently filtering Content-Length.

Thanks!

**Comment by joohoi** [comment] 2019-09-22 19:22
The regex matcher / filter should be working for response headers since v0.8.

**Comment by joohoi** [comment] 2019-09-22 19:23
I'm closing this issue as it should be a non-issue. If there's a reproducible bug however, feel free to comment, and I'll reopen the issue.

**Closed by joohoi** 2019-09-22 19:23 UTC

**Comment by pasikarkkainen** [comment] 2020-11-15 21:39
With quick testing it seems ffuf regexp filter indeed does *not* work against response headers.

**Comment by joohoi** [comment] 2020-11-16 00:03
It definitely should be working. I keep using it all the time. I wonder if you could provide me a reproduceable example so I could figure out if there's a corner case bug that you are hitting.
