### ISSUE TITLE
Ffuf Log shows the wrong Content-Length

### ISSUE THREAD

**Issue by electroxero** [ffuf/ffuf#427] opened 2021-04-18 22:12 UTC
# Description

 I have tried to run `ffuf` a couple of times on different targets and I have noticed that the `Content-Length`, named `size`, reported by the visual logger is different from the `Content-Length` response header.

## Example
![image](https://user-images.githubusercontent.com/20456461/115162402-a26b8180-a0a3-11eb-9f47-369afc0e51e6.png)

If you lunch the request using burp suite, the `Content-Length` response header is equal to: `5091`

![image](https://user-images.githubusercontent.com/20456461/115162445-cf1f9900-a0a3-11eb-9bf8-e9d58f0ec35a.png)

**Comment by joohoi** [comment] 2021-04-26 16:58
Thanks for opening the issue, I tested it out and this definitely is a bug. It's caused by ffuf counting the number of runes, which basically means UTF-characters which can in reality be multiple chars long.

I'll get it fixed in the near future.

**Closed** 2021-04-26 19:39 UTC
Labels: bug
