### ISSUE TITLE
Runtime issue

### ISSUE THREAD

**Issue by Th3R0oT** [ffuf/ffuf#314] opened 2020-09-29 17:50 UTC
root@kali:~/Downloads# go get -u github.com/ffuf/ffuf
# runtime
/usr/local/go/src/runtime/lockrank_off.go:28:2: undefined: lock2
/usr/local/go/src/runtime/lockrank_off.go:37:2: undefined: unlock2

**Comment by bsysop** [comment] 2020-09-29 18:29
Hi @Th3R0oT!

This looks a problem with your environment, could you please rename the title to something more readable and put here all the output of your "go get" command?

Thanks.

**Comment by Th3R0oT** [comment] 2020-09-29 19:41
root@kali:~# go get
can't load package: package .: no Go files in /root
root@kali:~#

**Comment by bsysop** [comment] 2020-09-29 20:19
I'm not sure if you are trolling, but.. could you give your go env please?
```
go env
```

**Comment by Th3R0oT** [comment] 2020-09-29 20:22
root@kali:~# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go-workspace"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build461729662=/tmp/go-build -gno-record-gcc-switches"

**Comment by joohoi** [comment] 2020-09-29 21:25
The error message implies that this is an issue with Go itself, not ffuf and most likely caused by your local go installation gone sour somehow.

**Comment by bsysop** [comment] 2020-09-29 23:26
Pretty much that, thank @joohoi 

@Th3R0oT you should check what's wrong with your environment, try a clean re-install!.

Happy hacking!.

**Comment by novinova** [comment] 2020-10-28 08:09
I had the same issue after downgrading go compiler version. It was because I unpacked old go version (1.11) archive without cleaning /usr/local/go (with 1.15) before it. Sol old and new files mixed all together without saving any consistency. Deleting of /usr/local/go (or where your compiler is situated) and reextraction helped.

**Comment by joohoi** [comment] 2021-05-17 14:51
Closing the issue in order to keep the issues backlog readable, and I do consider the issue either resolved or there's no communication. If you have something to add to the issue, please comment and we'll consider reopening it.

**Closed by joohoi** 2021-05-17 14:51 UTC
Labels: invalid, question
