### ISSUE TITLE
problem while running  ffuf

### ISSUE THREAD

**Issue by momocr7** [ffuf/ffuf#392] opened 2021-02-11 04:34 UTC
Hello, I do not know how this problem occurred but when I running with sample command like 
`ffuf -url example.com/FUZZ -w ~/mywordlist` 
the terminal output is like this and it keeps return new lines
![image](https://user-images.githubusercontent.com/40707762/107602410-46a6f700-6c21-11eb-9879-0cef45902150.png)

note that I had had backbox linux and it worked fine and just display the results but when I turned to parrot OS this problem appeared and I just want the results appear in the terminal as always like this:
![image](https://user-images.githubusercontent.com/40707762/107602697-596dfb80-6c22-11eb-8c3d-cbcaddb1e739.png)

**Comment by joohoi** [comment] 2021-02-11 07:26
Duplicate of #166

**Closed by joohoi** 2021-02-11 07:26 UTC
Labels: duplicate

**Comment by null-hyp0thesis** [comment] 2024-04-15 09:25
To silence the Progress bar, just output stderr to /dev/null
`ffuf -u http://10.10.10.10 -w wordlist.txt 2>/dev/null`

![image](https://github.com/ffuf/ffuf/assets/16426543/d6912c47-e307-4cdf-a99c-b9fec03e7b1c)
