### ISSUE TITLE
Missed directories by ffuf but found by dirb (same wordlist of course)

### ISSUE THREAD

**Issue by iNoSec2** [ffuf/ffuf#745] opened 2023-10-17 20:28 UTC
Hi, i use ffuf since a long time but today when dealing with a CTF challenge i saw ffuf missed a directory when dirb found it.
`ffuf -c -u http://challenge01.root-me.org/web-serveur/ch06/phpbb/FUZZ/ -w /usr/share/dirb/wordlists/common.txt`
the `install` dir isnt found by ffuf but found by dirb 
![image](https://github.com/ffuf/ffuf/assets/51358868/d9371566-26ec-4ca0-96a0-61927c6f46ed)

![image](https://github.com/ffuf/ffuf/assets/51358868/df7eba05-0077-420c-86b0-2332d6fef9f9)

Just to let you know since that's weird

**Comment by joohoi** [comment] 2023-10-22 14:07
Hmm, that's weird. I tried to log in to the service and tested it out. I cannot reproduce this (ffuf consistently does find it for me). 

The service does however enable access based on the source IP address when logging in and starting the challenge. I wonder if there was something wrong in that process when you ran the ffuf test.

I'm wondering this as in your screenshot you seem to have filtered out 403 responses, and the server definitely answers with 403 to everything if the ip based access is not enabled, while when it is, the typical answer for non-hits are just normal 404's.

**Comment by joohoi** [comment] 2023-10-22 14:08
I'm closing this issue now as there's no action points based on it. Feel free to comment in case I missed something here.

**Closed by joohoi** 2023-10-22 14:08 UTC
