### ISSUE TITLE
issue while running in windows

### ISSUE THREAD

**Issue by Droidzzzio** [ffuf/ffuf#238] opened 2020-05-12 13:38 UTC
Hey 
I don't know what issue is coming from last 15-20 days since i updated the tool to the latest version but every time i am running the tool , i am getting the same error.

Encountered error(s): 1 errors occured.
        * Keyword \Users\malav\Downloads\SecLists\dirb-list-2.3-medium.txt defined, but not found in headers, method, URL or POST data.

The issue is not coming if i am in the same directory in which the wordlist exist.

**Comment by joohoi** [comment] 2020-05-16 12:48
Closing as duplicate of #227

**Closed by joohoi** 2020-05-16 12:48 UTC
Labels: duplicate
